[tool.poetry]
name = "mds-toolbox"
version = "2.0.0"
description = "A custom CMCC library to list and download data from the Marine Data Store"
authors = ["Antonio Mariani <antonio.mariani@cmcc.it>"]
readme = ["README.md"]
packages = [
    { include = "mds" },
    { include = "mds/**/*.py" },
]
keywords = ["copernicus", "copernicusmarine", "mds", "marine data store"]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
boto3 = "^1.37.4"
copernicusmarine = ">=2.1.1"
click = "^8.1.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
mds = "mds.mng:start_from_command_line_interface"
