[project]
name = "pythonanywhere-tools"
version = "0.1.002"
description = "Simple set of tools to, reload the webserver, or extend for 3 months the free tier programatically."
authors = [{ name="Manuel Seromenho", email="manuelseromenho@gmail.com" }]
readme = "README"
license = "MIT"
requires-python = ">=3.10"
dependencies = ["requests", "python-dotenv"]

[project.urls]
Homepage = "https://github.com/manuelseromenho/pythonanywhere_tools"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
