[project]
name = "jinja-i18n-tools"
version = "0.1.1"
description = "Automated i18n tool for Jinja2 projects using Babel and Google Translate"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "Tamer OnLine", email = "info@tameronline.com" }
]
dependencies = [
  "jinja2 >=3.1.0",
  "babel >=2.9.1",
  "deep-translator >=1.11.4",
  "polib >=1.1.1"
]
requires-python = ">=3.12"

[project.scripts]
jinja-i18n = "jinja_i18n_tools.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["jinja_i18n_tools"]
include-package-data = true

[tool.setuptools.package-data]
jinja_i18n_tools = ["*.cfg"]
