[project]
name = "justsdk"
version = "1.2.0"
description = "Just DEV."
readme = "README.md"
authors = [
    { name = "eesuhn", email = "eason.yihong@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pyyaml>=6.0.2",
]

[project.scripts]
justsdk = "justsdk:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]
