[project]
name = "ngpt"
version = "4.0.1"
description = "A Swiss army knife for LLMs: A fast, lightweight CLI and interactive chat tool that brings the power of any OpenAI-compatible LLM (OpenAI, Ollama, Groq, Claude, Gemini, etc.) straight to your terminal. rewrite texts or refine code, craft git commit messages, generate and run OS-aware shell commands."
authors = [
    {name = "nazDridoy", email = "nazdridoy399@gmail.com"},
]
dependencies = [
    "requests>=2.31.0",
    "rich>=10.0.0",
    "prompt_toolkit>=3.0.0",
    "pyperclip>=1.8.0",
    "beautifulsoup4>=4.12.0",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}
keywords = ["openai", "cli", "api-client", "llm", "ai", "gpt", "chatgpt", "chatbot", "cli-tool", "shell-commands", "git-commit", "code-generation", "text-rewriting", "markdown-rendering", "groq", "ollama", "claude"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Topic :: Communications :: Chat",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Internet :: WWW/HTTP",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: System Administrators",
]

[project.urls]
"Homepage" = "https://github.com/nazdridoy/ngpt"
"Repository" = "https://github.com/nazdridoy/ngpt"
"Bug Tracker" = "https://github.com/nazdridoy/ngpt/issues"

[project.scripts]
ngpt = "ngpt.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
