[project]
name = "django-prod"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "MayasNova", email = "code@mayasnova.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=4.2",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.1.0",
    "questionary>=2.1.0",
    "scp>=0.15.0",
    "whitenoise>=6.9.0",
]

[project.scripts]
django-prod = "django_prod:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
