[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "BoPlotKit"
version = "0.1.6"
description = "An advanced and flexible scientific plotting toolkit."
readme = "README.md"
requires-python = ">=3.7"
license = { text = "GNU General Public License v3 (GPLv3)" }
authors = [
  { name="Bo Qian", email="bqian@shu.edu.cn" }
]
dependencies = [
  "matplotlib>=3.0",
  "numpy>=1.18",
  "pandas>=1.0",
  "pytest>=6.0"
]

[project.urls]
Homepage = "https://github.com/bo-qian/BoPlotKit"
Repository = "https://github.com/bo-qian/BoPlotKit"