[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anyeval"
version = "0.1.6"
description = "Universal Evaluation for Gen AI"
readme = "README.md"
requires-python = ">=3.10"
license = { file = "LICENSE" }
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn>=0.23.2",
    "pydantic>=2.4.2",
    "typer>=0.9.0",
    "pandas>=2.0.0",
    "pyarrow>=14.0.0",
    "opendal>=0.45.19",
    "duckdb>=1.2.0",
]

[project.scripts]
anyeval = "anyeval.cli.main:app"

[tool.setuptools]
include-package-data = true
packages = ["anyeval", "anyeval.cli", "anyeval.backend"]

[tool.hatch.version]
path = "anyeval/backend/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["anyeval"]
include = ["anyeval/backend/static/*"]

[dependency-groups]
dev = [
    "ruff>=0.11.10",
    # used in create_sample_data.py
    "pillow>=10.0.0",
    "imageio[ffmpeg]>=2.31.0",
    "numpy>=1.24.0",
]
