[project]
name = "magic-moonshine"
version = "1.2.8"
description = "A powerful text-based video editing tool"
authors = [{ name = "Moonshine", email = "python@usemoonshine.com" }]
license = { text = "MIT" }
readme = "README.md"
dependencies = [
    "setuptools>=61.0",
    "wheel"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
