[project]
name = "nilai-py"
version = "0.1.0rc1"
description = "Nilai Python SDK"
readme = "README.md"
authors = [
    { name = "JosÃ© Cabrero-Holgueras", email = "jose.cabrero@nillion.com" }
]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "nuc",
    "openai>=1.86.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
nuc = { git = "https://github.com/NillionNetwork/nuc-py.git", tag = "35ca10c49f861dc27968a36e5b7fb00cfc5188c2"}

[dependency-groups]
dev = [
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.13",
]
