[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "PiMath"
version = "0.8.0"
description = "A math library"
readme = "README.md"
authors = [{ name = "Ãlvaro Perseo", email = "ayuskyap@gmail.com" }]
requires-python = ">=3.9"
keywords = ["math", "geometry", "numbers"]
license = {text = "MIT License"}
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Mathematics"
]
dependencies = [
    "matplotlib",
]

[project.urls]
Homepage = "https://github.com/Pygramer78/PiMath"