# pyproject.toml
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scpygen"
version = "1.0.0"
description = "A python project structure generator"
readme = "README.md"
requires-python = ">=3.7"

[project.scripts]
scpygen = "scpygen.cli:main"