[tool.poetry]
name = "cmk-tools"
version = "2.1.1"
description = ""
authors = ["NhanDD3 <nhandd3@fpt.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
redis = "^5.1.1"
pytest = "^8.3.3"
bump2version = "^1.0.1"
python-json-logger = "^2.0.7"
requests = "^2.32.3"
elasticsearch = "7.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
