[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "houghvg"                # Le nom de ton package sur PyPI (doit être unique)
version = "0.1.0"
description = "Une boîte à outils de la Transformée de Hough basée sur les grilles virtuelles"
readme = "README.md"
license = {text = "MIT"}
authors = [
  { name="Ton Nom", email="moisewedra@gmail.com" }
]
requires-python = ">=3.7"
dependencies = ['numpy>=1.24.2','opencv-contrib-python>=4.7.0.72','pymp-pypi>=0.5.0','matplotlib>=3.6.3', 'scipy>=1.10.1','scikit-image>=0.21.0']

[project.urls]
Homepage = "https://github.com/moise-github/houghvg"