[build-system]
requires = ['setuptools>=61.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'piegy'
version = '2.0.1'
description = 'Payoff-Driven Stochastic Spatial Model for Evolutionary Game Theory'
readme = 'README.md'
requires-python = '>=3.6'
license = {file = "LICENSE.txt"}
authors = [
    {name = 'Chenning Xu', email = 'cxu7@caltech.edu'}
]
keywords = ['Game Theory', 'Evolutionary Game Theory', 'Spatial Model', 'Stochastic Model', 'Payoff Driven']
dependencies = [
    'numpy',
    'matplotlib',
    'moviepy>=2.1.1',
    'seaborn>=0.13.2'
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent"
]


[project.urls]
Source = 'https://github.com/Chenning04/piegy.git'
Documentation = 'https://piegy.readthedocs.io/en/'

[tool.setuptools]
package-dir = {'' = 'src'}

[tool.setuptools.packages.find]
where = ['src']

[tool.setuptools.package-data]
"piegy" = ["C_core/piegyc.so"]


