[project]
name = "yanki"
dynamic = ["readme", "version"]
description = "Build Anki decks from text files containing YouTube URLs."
authors = [{name = "Daniel Parks", email = "oss-yanki@demonhorse.org"}]
requires-python = ">= 3.11"
license = "MIT OR Apache-2.0"
license-files = ["LICENSE-*"]
keywords = ["anki", "flashcards"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Education",
    "License :: OSI Approved :: Apache Software License",
    "License :: OSI Approved :: MIT License",
    "Topic :: Education",
]

dependencies = [
    "yt-dlp >=2024.11.4",
    "genanki >=0.13.1,<0.14",
    "docutils >=0.21.2,<0.22",
    "ffmpeg-python >=0.2.0,<0.3",
    "colorlog >=6.9.0,<7.0",
    "click >=8.1.8,<9.0",
    "mistletoe>=1.4.0",
]

[dependency-groups]
dev = [
    "pytest~=8.3",
    "ruff>0.8.4",
    "pre-commit>=4.0.1,<5",
    "pytest-console-scripts>=1.4.1,<2",
    "psutil>=6.1.1,<7",
]

[project.urls]
Homepage = "https://github.com/danielparks/yanki"
Issues = "https://github.com/danielparks/yanki/issues"

[project.scripts]
yanki = "yanki.cli:main"

[tool.pytest.ini_options]
log_cli_level = "DEBUG"

[tool.ruff]
line-length = 80

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
    "A",        # I donâ€™t mind shadowing built-ins.
    "ANN",      # FIXME? type annotations.
    "B019",     # FIXME: `functools.cache` can leak memory.
    "COM812",   # Conflicts with formatter.
    "CPY",      # I donâ€™t want copyright notices at the top of every file.
    "D1",       # FIXME: Undocumented public items.
    "DOC",      # FIXME: Undocumented returns, raises, etc.
    "EM",       # I donâ€™t like the `msg = ...; raise Error(msg)` syntax.
    "FIX",      # I like FIXME comments for low-priority stuff.
    "G004",     # I prefer f-strings for logging for clarity.
    "PLC1901",  # Explicit comparisons to `""` are often clearer.
    "PLR0904",  # FIXME? Too many public methods.
    "PLR0911",  # I donâ€™t care about too many returns.
    "PLR2004",  # â€œMagicâ€ values often easier to understand without a CONSTANT.
    "PLR6301",  # Too many false positive (methods that donâ€™t need `self`).
    "PLW2901",  # I like to shadow `for` loop variables.
    "PT011",    # `pytest.raises(...)` is too broad: Too many false positives.
    "S404",     # I use `subprocess`.
    "S603",     # This seems to trigger on all calls to `subprocess.run`.
    "T20",      # We use `print()`.
    "TD",       # I prefer my FIXME format.
    "TRY003",   # Itâ€™s a lot more work to have separate error classes.
    "UP015",    # I prefer to be explicit about opening files for reading.

    # I frequently use characters that trigger these lints like "â€™"  and "â¯":
    "RUF001", "RUF002", "RUF003",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
  "INP001", # Don't care about implicit namespace in tests.
  "S101",   # assert is fine in tests.
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.hatch.build.targets.wheel]
packages = ["yanki"]

[tool.hatch.version]
path = "yanki/__version__.py"

[build-system]
requires = ["hatchling", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.sdist]
include = [
  "/REFERENCE.adoc",
  "/test-decks",
  "/tests",
  "/uv.lock",
  "/web-files",
  "/yanki",
]

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"
fragments = [{path = "README.md"}]

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# Remove GitHub only sections from README.md.
pattern = '(?s)<!-- GitHub only -->.+<!-- /GitHub only -->'
replacement = ''

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# Replace GitHub-specific [!TIP] syntax.
pattern = '\[!TIP\]'
replacement = '### ðŸ’¡ Tip'

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
# Make links to package files absolute GitHub links.
pattern = '(?m)^(\[.+?\]):\s*((?!\w+:)\S+)'
replacement = '\1: https://github.com/danielparks/yanki/blob/v$HFPR_VERSION/\2'
