[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adbauto"
version = "0.0.12"
description = "A Python ADB automation library for Android emulators."
authors = [{ name="Thomas Knoops" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.8"
dependencies = [
    "opencv-python",
    "numpy"
]

[project.urls]
Homepage = "https://github.com/ThomasKnoops/adbauto"
Repository = "https://github.com/ThomasKnoops/adbauto"

[tool.setuptools]
include-package-data = true
packages = ["adbauto", "adbauto.scrcpy"]
