[project]
name = "P2Ray"
version = "0.0.1.3"
description = "A V2ray vpn Client with a focus on config managment"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "LICENSE"}
authors = [{name = "Parsa Roshanak", email = "parsaroshanak@gmail.com"}]
dependencies = [
    "emoji>=2.14.1",
    "Pillow>=11.2.1",
    "pyperclip>=1.9.0",
    "qrcode>=8.2",
    "Requests>=2.32.4",
    "tabulate>=0.9.0",
    "appdirs>=1.4.4"
]

[project.urls]
"Homepage" = "https://github.com/iparsw/P2Ray"
"Bug Tracker" = "https://github.com/yourname/iparsw/P2Ray"

# âœ… For script-style entry point (optional)
[project.scripts]
mytool = "p2ray.__main__:main"