[project]
name = "kalkulator-ngaco"
version = "0.1.1"
description = "Kalkulator ngawur tapi lucu. Jangan percaya hasilnya."
authors = [{ name = "Nama Kamu", email = "email@example.com" }]
readme = "README.md"
requires-python = ">=3.7"
dependencies = []

[project.scripts]
kalkulator-ngaco = "kalkulator_ngaco.__main__:main"
