[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "octopusdash"
version = "0.1.1"
description = "A modern open-source Django admin dashboard."
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
  { name="Hussein Naeem", email="husseinnaeemsec@gmail.com" }
]
dependencies = [
  "Django>=4.0",
]

[project.urls]
Homepage = "https://github.com/husseinnaeemsec/octopusdash"
Repository = "https://github.com/husseinnaeemsec/octopusdash"
