# setuptools pyproject.toml for a project called "vertagus" that is a
# Python package

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "vertagus"
version = "0.2.2"
description = "A tool to assist the maintenance of package versioning with scm tags"
readme = "README.md"
authors = [
    {"name" = "John Raines", "email" = "johndanielraines@gmail.com"}
]
dependencies = [
    "click",
    "GitPython",
    "tomli",
    "packaging",
    "PyYAML>=6"
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Topic :: Software Development",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/jdraines/vertagus"
Documentation = "https://github.com/jdraines/vertagus/blob/main/docs/index.md"
Repository = "https://github.com/jdraines/vertagus"
"Bug Tracker" = "https://github.com/jdraines/vertagus/issues"

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]
qa = [
    "pytest",
    "pytest-cov",
]

[project.scripts]
vertagus = "vertagus.cli:cli"

