[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "SUILib"
version = "0.1.1"
description = "Simple UI Library for Pygame applications"
authors = [
    { name = "Martin Krcma", email = "martin.krcma1@gmail.com" }
]
urls = { "Homepage" = "https://github.com/0xMartin/SUILib" }
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pygame",
    "matplotlib",
    "numpy"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["SUILib*"]