[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optpricing"
version = "2.1.0"
authors = [
  { name="Diljit Singh", email="first_last22@google.com" },
]
description = "A financial options pricing and analysis library."
readme = "README.md"
requires-python = ">=3.10"
license = { file="LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Office/Business :: Financial :: Investment",
]

dependencies = [
    "numpy~=2.2.5",
    "scipy~=1.15.2",
    "pandas~=2.2.3",
    "numba~=0.61.2",
    "pyyaml~=6.0.2",
    "click~=8.1",
    "typer~=0.15.2",
    "streamlit~=1.45.1",
    "matplotlib~=3.10.1",
    "plotly~=6.1.2",
    "yfinance~=0.2.63",
    "tabulate~=0.9.0",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "ruff",
    "mkdocs",
    "mkdocs-material",
    "mkdocstrings[python]",
    "mkdocs-section-index",
    "line_profiler",
]

[project.urls]
"Homepage" = "https://diljit22.github.io/quantfin/"

[project.scripts]
optpricing = "optpricing.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
extend-exclude = ["demo"]

[tool.ruff.lint]
select = ["E", "W", "F", "I", "N", "UP", "NPY"]
ignore = ["N803", "N806", "E731", "F841", "NPY002", "F401", "F403", "F405", "N999"]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["S101"]

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = false

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=src/optpricing --cov-report=term-missing"
testpaths = ["tests"]