[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
version = "2025.06.30"
name = "syndrilla"
authors = [
  { name="Yanzhang Zhu", email="yanzhang.zhu@ucf.edu" },
  { name="Di Wu", email="di.wu@ucf.edu" },
]
description = "A PyTorch-based numerical simulator for decoders in quantum error correction."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python"
]

dependencies = [
    "pyyaml",
    "yamlordereddictloader",
    "loguru",
    "numpy",
    "scipy",
    "pyfiglet",
    "torch>=2.0"
]

[tool.hatch.build.targets.wheel]
include = ["src/**"]

[project.scripts]
syndrilla = "src.main:main"

[project.urls]
Homepage = "https://github.com/UNARY-Lab/syndrilla"
Issues = "https://github.com/UNARY-Lab/syndrilla/issues"
