[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "piredactor"
version = "0.1.5"
authors = [{ name = "Piyush Chauhan", email = "piyush23321@gmail.com" }]
description = "A flexible Python package for redacting Personally Identifiable Information (PII) from dictionaries and lists using a schema-based approach."
readme = "README.md"
requires-python = ">=3.7"
license = { file = "LICENSE" }
keywords = [
    "pii",
    "redact",
    "privacy",
    "decorator",
    "schema",
    "gdpr",
    "security",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Security",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

dependencies = ["PyYAML>=5.0"]

# --- ADD THIS SECTION ---
[tool.setuptools.package-data]
piredactor = ["*.json"]