[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pg-xmat"
version = "0.1.2"
authors = [{ name = "Daniel Grant" }]
description = "Cross-database materialisations for Postgres"
readme = "README.md"
requires-python = ">=3.7"
dependencies = ["psycopg2-binary", "pydantic"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Database",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
]

[project.optional-dependencies]
dev = ["ruff", "twine", "build"]

[tool.setuptools]
package-dir = { "" = "src" }
py-modules = ["pg_xmat", "schemas", "utils"]

[project.scripts]
pg-xmat = "pg_xmat:main"
