[project]
name = "egeometry"
requires-python = ">=3.12"
version = "0.13.0"
description = "Python geometry library."
authors = [
    {name = "Erik Soma", email= "stillusingirc@gmail.com"}
]

[tool.poetry.build]
generate-setup-file = false

[tool.poetry.dependencies]
python = "^3.12"
emath = "^0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.1.1"

[build-system]
requires = ["poetry-core", "setuptools==69.0.2", "jinja2==3.1.2"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true

[tool.pyright]
venvPath = "."
venv = ".venv"
