[project]
name = "igipy"
version = "0.1.3"
description = "Reverse engineering tools for 'Project IGI' game"
readme = "README.md"
authors = [
    { name = "artiom.rotari", email = "artiom.rotari@ebs-integrator.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "tabulate>=0.9.0",
    "typer>=0.16.0",
]

[project.scripts]
igipy = "igipy.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
lint = [
    "ruff>=0.12.0",
]

[tool.ruff]
line-length = 120
lint.select = ["ALL"]
lint.ignore = ["D", "COM812"]
