[project]
name = "red-tidegear"
description = "A small collection of utilities for cog creation with Red-DiscordBot."
authors = [{ name = "cswimr", email = "seaswimmertehfsh@gmail.com" }]
requires-python = ">=3.9,<3.12"
license = "MPL-2.0"
license-files = ["LICEN[CS]E*"]
classifiers = [
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "pip",                   # Red-DiscordBot depends on pip but doesn't list it as a dependency. Ensure it's installed; version is irrelevant.
  "furl>=2.1.4",
  "red-discordbot>=3.5.6",
]
dynamic = ["readme", "version", "urls"]

[project.optional-dependencies]
pydantic = ["pydantic>=2.11.0"]

[dependency-groups]
dev = ["basedpyright>=1.29.4", "ruff>=0.12.0"]

[tool.hatch.build]
include = ["/tidegear"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "tidegear/version.py"
template = """
# This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
# If a copy of the MPL was not distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Â© 2025 cswimr

# This file is automatically generated on build, do not edit!
# Do not commit this file to source control!

from furl import furl

from .metadata import Repository, SemVer, TidegearMeta

meta = TidegearMeta(
    version=SemVer.from_tuple({version_tuple}),
    repository=Repository(
        owner="cswimr",
        name="tidegear",
        url=furl("https://c.csw.im/cswimr/tidegear"),
    ),
)

version = meta.version
__version__ = str(meta.version)
"""

[tool.hatch.metadata.hooks.vcs.urls]
Homepage = "https://c.csw.im/cswimr/tidegear"
Issues = "https://c.csw.im/cswimr/tidegear/issues"
source_archive = "https://c.csw.im/cswimr/tidegear/archive/{commit_hash}.tar.gz"

[tool.hatch.metadata.hooks.fancy-pypi-readme]
content-type = "text/markdown"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.fragments]]
path = "README.md"

[[tool.hatch.metadata.hooks.fancy-pypi-readme.substitutions]]
pattern = '\[(.+?)\]\(((?!https?://)\S+?)\)'
replacement = '[\1](https://c.csw.im/cswimr/tidegear/src/tag/v$HFPR_VERSION\g<2>)'

[build-system]
requires = ["hatchling", "hatch-vcs", "hatch-fancy-pypi-readme"]
build-backend = "hatchling.build"

[tool.basedpyright]
typeCheckingMode = "standard"
reportImplicitOverride = "warning"

[tool.ruff]
line-length = 150
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
select = [
  "I",
  "N",
  "F",
  "W",
  "E",
  "G",
  "A",
  "COM",
  "INP",
  "T20",
  "PLC",
  "PLE",
  "PLW",
  "PLR",
  "LOG",
  "SLF",
  "ERA",
  "FIX",
  "PERF",
  "C4",
  "EM",
  "RET",
  "RSE",
]
ignore = [
  "PLR0911",
  "PLR0912",
  "PLR0915",
  "PLR2004",
  "PLR0913",
  "EM101",
  "COM812",
]
fixable = ["ALL"]
unfixable = []

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
