[build-system]
build-backend = "hatchling.build"
requires = ["hatchling >= 1.26"]

[project]
dependencies = ["bs4", "requests"]
description = "A web scraper that lists items from Findmestore."
license = "MIT"
license-files = ["LICEN[CS]E*"]
name = "fmslist"
readme = "README.md"
requires-python = ">=3.9"
version = "0.0.2"

[project.urls]
Homepage = "https://github.com/d4n1elchen/fmslist"
Issues = "https://github.com/d4n1elchen/fmslist/issues"
