[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jadio-publisher"
dynamic = ["version"]
description = "Jadio-compatible extension package"
readme = "README.md"
license = "MIT"
requires-python = ">=3.8"
dependencies = [
    "jadio>=0.0.2",
]

[project.scripts]
jpub = "jadio_publisher.cli.main:main"

[tool.hatch.version]
path = "src/jadio_publisher/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/jadio_publisher"]
