[project]
name = "envlock"
version = "1.0.0"
description = "A secure CLI tool for encrypting, decrypting, shredding, and rotating secrets files using strong symmetric encryption."
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "Nikhil John", email = "me@nikz.in"}
]
license = "MIT"
license-files = ["LICENSE*"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Environment :: Console",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries :: Python Modules"
]
keywords = ["encryption", "secrets", "cli", "security", "cryptography", "locker", "vault", "file", "python"]
dependencies = [
    "click>=8.2.1",
    "cryptography>=45.0.4",
]

[project.scripts]
envlock = "main:cli"

[dependency-groups]
dev = [
    "build>=1.2.2.post1",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.14",
    "twine>=6.1.0",
]

[project.urls]
Homepage = "https://github.com/nikhiljohn10/envlock"
Issues = "https://github.com/nikhiljohn10/envlock/issues"

[build-system]
requires = ["setuptools>=80.9"]
build-backend = "setuptools.build_meta"

[project.optional-dependencies]
test = [
    "pytest>=8.4.1",
    "pytest-cov>=5.0.0"
]

[tool.pytest.ini_options]
addopts = "--maxfail=1 --cov=main --cov-report=term-missing"

[tool.setuptools]
py-modules = ["main"]
